# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/node

    working_directory: ~/repo

    steps:
      - run:
          name: run spec1
          command:  |
            curl --header "Content-Type: application/json" \
            --request POST \
            --data '{"arguments":"-- --params.testrun_id=3 --specs=\"tests/scenarios/uiTests/smoke/spec1.js\" --params.token=\"b7e837ba-a1b7-4bce-a92b-44976c7544561569573601172\""}' \
            https://1pcknb3954.execute-api.us-east-2.amazonaws.com/default/ExecuteTests
      - run:
          name: run spec2
          command:  |
            curl --header "Content-Type: application/json" \
            --request POST \
            --data '{"arguments":"-- --params.testrun_id=3 --specs=\"tests/scenarios/uiTests/smoke/spec2.js\" --params.token=\"b7e837ba-a1b7-4bce-a92b-44976c7544561569573601172\""}' \
            https://1pcknb3954.execute-api.us-east-2.amazonaws.com/default/ExecuteTests
      - run:
          name: run spec3
          command:  |
            curl --header "Content-Type: application/json" \
            --request POST \
            --data '{"arguments":"-- --params.testrun_id=3 --specs=\"tests/scenarios/uiTests/smoke/spec3.js\" --params.token=\"b7e837ba-a1b7-4bce-a92b-44976c7544561569573601172\""}' \
            https://1pcknb3954.execute-api.us-east-2.amazonaws.com/default/ExecuteTests
      - run:
          name: run spec4
          command:  |
            curl --header "Content-Type: application/json" \
            --request POST \
            --data '{"arguments":"-- --params.testrun_id=3 --specs=\"tests/scenarios/uiTests/smoke/spec4.js\" --params.token=\"b7e837ba-a1b7-4bce-a92b-44976c7544561569573601172\""}' \
            https://1pcknb3954.execute-api.us-east-2.amazonaws.com/default/ExecuteTests
      - run:
          name: run spec5
          command:  |
            curl --header "Content-Type: application/json" \
            --request POST \
            --data '{"arguments":"-- --params.testrun_id=3 --specs=\"tests/scenarios/uiTests/smoke/spec5.js\" --params.token=\"b7e837ba-a1b7-4bce-a92b-44976c7544561569573601172\""}' \
            https://1pcknb3954.execute-api.us-east-2.amazonaws.com/default/ExecuteTests
      - run:
          name: run spec6
          command:  |
            curl --header "Content-Type: application/json" \
            --request POST \
            --data '{"arguments":"-- --params.testrun_id=3 --specs=\"tests/scenarios/uiTests/smoke/spec6.js\" --params.token=\"b7e837ba-a1b7-4bce-a92b-44976c7544561569573601172\""}' \
            https://1pcknb3954.execute-api.us-east-2.amazonaws.com/default/ExecuteTests
      - run:
          name: run spec7
          command:  |
            curl --header "Content-Type: application/json" \
            --request POST \
            --data '{"arguments":"-- --params.testrun_id=3 --specs=\"tests/scenarios/uiTests/smoke/spec7.js\" --params.token=\"b7e837ba-a1b7-4bce-a92b-44976c7544561569573601172\""}' \
            https://1pcknb3954.execute-api.us-east-2.amazonaws.com/default/ExecuteTests
      - run:
          name: run spec8
          command:  |
            curl --header "Content-Type: application/json" \
            --request POST \
            --data '{"arguments":"-- --params.testrun_id=3 --specs=\"tests/scenarios/uiTests/smoke/spec8.js\" --params.token=\"b7e837ba-a1b7-4bce-a92b-44976c7544561569573601172\""}' \
            https://1pcknb3954.execute-api.us-east-2.amazonaws.com/default/ExecuteTests
      - run:
          name: run spec9
          command:  |
            curl --header "Content-Type: application/json" \
            --request POST \
            --data '{"arguments":"-- --params.testrun_id=3 --specs=\"tests/scenarios/uiTests/smoke/spec9.js\" --params.token=\"b7e837ba-a1b7-4bce-a92b-44976c7544561569573601172\""}' \
            https://1pcknb3954.execute-api.us-east-2.amazonaws.com/default/ExecuteTests
      - run:
          name: run spec10
          command:  |
            curl --header "Content-Type: application/json" \
            --request POST \
            --data '{"arguments":"-- --params.testrun_id=3 --specs=\"tests/scenarios/uiTests/smoke/spec10.js\" --params.token=\"b7e837ba-a1b7-4bce-a92b-44976c7544561569573601172\""}' \
            https://1pcknb3954.execute-api.us-east-2.amazonaws.com/default/ExecuteTests