# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/node

    working_directory: ~/repo

    steps:
      - run curl --header "Content-Type: application/json" \
          --request POST \
          --data '{"arguments":"-- --params.testrun_id=2 --params.token=\"b7e837ba-a1b7-4bce-a92b-44976c7544561569573601172\""}' \
          https://1pcknb3954.execute-api.us-east-2.amazonaws.com/default/ExecuteTests